version: '2'
services:
  gestionpatient-app:
    image: gestionpatient
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://gestionpatient-mysql:3306/gestionpatient?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://gestionpatient-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://gestionpatient-elasticsearch:9200
    ports:
      - 8084:8084
  gestionpatient-mysql:
    extends:
      file: mysql.yml
      service: gestionpatient-mysql
  gestionpatient-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: gestionpatient-elasticsearch
